### ISSUE TITLE
Crash when starting the overlay on a device running Android O preview

### ISSUE THREAD

**Issue by alt236** [alt236/Floating-Info---Android#2]
```
                   --------- beginning of crash
06-18 23:21:38.217 3544-4535/uk.co.alt236.floatinginfo E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                     Process: uk.co.alt236.floatinginfo, PID: 3544
                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                         at android.os.AsyncTask$3.done(AsyncTask.java:325)
                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                         at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                         at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                         at java.lang.Thread.run(Thread.java:764)
                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                         at uk.co.alt236.floatinginfo.data.access.generalinfo.inforeader.cpu.CpuUtilisationReader.getCpuInfo(CpuUtilisationReader.java:105)
                         at uk.co.alt236.floatinginfo.data.access.generalinfo.MonitorTask$InnerTask.getCpuData(MonitorTask.java:133)
                         at uk.co.alt236.floatinginfo.data.access.generalinfo.MonitorTask$InnerTask.doInBackground(MonitorTask.java:93)
                         at uk.co.alt236.floatinginfo.data.access.generalinfo.MonitorTask$InnerTask.doInBackground(MonitorTask.java:67)
                         at android.os.AsyncTask$2.call(AsyncTask.java:305)
                         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                         at java.lang.Thread.run(Thread.java:764) 
```

**Comment by alt236** [comment]
SELinux has blocked access to "/proc/stat"
